// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnK6YmdAnuvjmcsOuCYQTRlFGcsgJp2JU',
    appId: '1:261648739862:web:37386b3fea160e48d2cf37',
    messagingSenderId: '261648739862',
    projectId: 'fruit-hup-store-4d53d',
    authDomain: 'fruit-hup-store-4d53d.firebaseapp.com',
    storageBucket: 'fruit-hup-store-4d53d.firebasestorage.app',
    measurementId: 'G-KLM53Q13VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_ukXZluvqzYoN349DVbQZ4kGyOraUuRg',
    appId: '1:261648739862:android:164d879e8c7cd4dad2cf37',
    messagingSenderId: '261648739862',
    projectId: 'fruit-hup-store-4d53d',
    storageBucket: 'fruit-hup-store-4d53d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-naNZPJtr8IT3mn5RShxR1djDJNSPQQs',
    appId: '1:261648739862:ios:712c6c52ca242c02d2cf37',
    messagingSenderId: '261648739862',
    projectId: 'fruit-hup-store-4d53d',
    storageBucket: 'fruit-hup-store-4d53d.firebasestorage.app',
    iosBundleId: 'com.example.fruitHupStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-naNZPJtr8IT3mn5RShxR1djDJNSPQQs',
    appId: '1:261648739862:ios:712c6c52ca242c02d2cf37',
    messagingSenderId: '261648739862',
    projectId: 'fruit-hup-store-4d53d',
    storageBucket: 'fruit-hup-store-4d53d.firebasestorage.app',
    iosBundleId: 'com.example.fruitHupStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnK6YmdAnuvjmcsOuCYQTRlFGcsgJp2JU',
    appId: '1:261648739862:web:a6ea9d735fa8ad36d2cf37',
    messagingSenderId: '261648739862',
    projectId: 'fruit-hup-store-4d53d',
    authDomain: 'fruit-hup-store-4d53d.firebaseapp.com',
    storageBucket: 'fruit-hup-store-4d53d.firebasestorage.app',
    measurementId: 'G-W585P7JTED',
  );
}
